# Docker containers used for development only.

services:
    mongo:
        # container_name: afd-mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongo:/data/db
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
        #     MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
        command: --replSet rs0

    mongoclient:
        # container_name: afd-mongo
        image: mongo
        depends_on:
            - mongo
        volumes:
            - ./dev_scripts:/dev_scripts
        # environment:
        #     MONGO_USERNAME: "${DB_USER}"
        #     MONGO_PASSWORD: "${DB_PASSWORD}"
        entrypoint:
            - /dev_scripts/initiate_replica.sh

version: "3"
